### ISSUE TITLE
usages of error_span! is filling up my log

### ISSUE THREAD

**Issue by smroid** [RReverser/ascom-alpaca-rs#1]
Example: src/server/mod.rs, line 102 creates a tracing::error_span! for every Alpaca request. This is causing a ton of "errors" (not really errors) to be logged.

Can these be downgraded to debug_span?

**Comment by RReverser** [comment]
Spans themselves should only provide "backtraces" for actual logs, they shouldn't appear in logs on their own if there was no log emitted.

What does your tracing subscriber look like? Did you accidentally enable something like `with_span_events()`?

**Comment by smroid** [comment]
My application makes no reference to tracing. It's not in my Cargo.toml, so the way I'm picking up tracing is via ascom-alpaca.

My main() function sets up logging as:
env_logger::Builder::from_env(                                                                  
   env_logger::Env::default().default_filter_or("info")).init();

Is there something I should be adding to my main() to configure trace logging?

**Comment by RReverser** [comment]
> Is there something I should be adding to my main() to configure trace logging?

Yes, see the docs: https://github.com/RReverser/ascom-alpaca-rs#logging-and-tracing

Basically you should be using tracing-subscriber or similar crates instead of env-logger. The `tracing`-based infrastructure is backward-compatible with `log` crate (e.g. it will print messages from `log` just like `env_logger` does) but it's more advanced and allows structural logging and more granular filters.

**Comment by smroid** [comment]
That solves it, thanks!

**Comment by RReverser** [comment]
Awesome. Out of curiosity, what are you building?

**Comment by smroid** [comment]
An e-finder. Information flow is sky -> camera -> star detect/locate -> plate solve -> Sky Safari

I'm using alpaca to publish the plate solver's RA/DEC for Sky Safari to indicate as the telescope position.

A similar project is https://github.com/githubdoe/skysolve. Mine's not published yet.

**Comment by RReverser** [comment]
Ah nice, yeah I had a sky solver written in Rust too but never published either as other stuff got in the way.

I don't think ASCOM or Alpaca protocol allows star solvers though? The integrations are usually implemented manually on per-app basis.

**Comment by smroid** [comment]
For the plate solving I'm using Tetra3, it works well. It might be nice to have a Rust solution though, how far along was your solver?

Regarding Alpaca, I'm presenting as a Telescope server and I implement the right_ascension() and declination() methods; this is enough for SkySafari to show my solved position.

**Comment by RReverser** [comment]
> It might be nice to have a Rust solution though, how far along was your solver?

I got into the usual ADHD-y state of "solved the hard problem and got bored and never finished last bits" 😄 It works reasonably well for long-focus images but at some point I started obsessing about solving for wide-field, accounting for distortions and such and never finished that bit.

I should get around and publish it anyway though.

FWIW it's very similar to ASTAP and was heavily inspired by it, so it's fast like ASTAP is (faster, actually), but has similar limitations in that you need to manually tweak config sometimes for solving to work correctly.
