### ISSUE TITLE
ASCOMError PartialEq

### ISSUE THREAD

**Issue by ivonnyssen** [RReverser/ascom-alpaca-rs#2]
Hi, 
thank you for this library! Awesome work! I am using it to implement an alpaca driver for QHYCCD cameras and filter wheels here: https://github.com/ivonnyssen/qhyccd-alpaca-rs.

I was wondering if ASCOMError could implement PartialEq? This would allow the use of assert_eq! on ASCOMResult, which would simplify test code.

Thank you!
Igor

**Comment by RReverser** [comment]
Glad to hear you're finding it useful!

Yeah I don't mind. On the other hand, I wonder if it's better for the test code to compare `.code` not the entire thing, since built-in messages  can change between versions.

**Comment by ivonnyssen** [comment]
I think just comparing .code would be good. If for some reason I want to check on the actual message, I can always compare the .to_string() results.

**Comment by RReverser** [comment]
Right, but what I meant is, at that point can you compare `.code` in your tests instead of us adding `PartialEq` to `ASCOMError` itself?

My main concern with adding this too soon is that, whichever behaviour it's implemented, it might be surprising to some users (those who expect message to be compared too vs those who expect error to stay exactly same between versions).

We might still revisit this in the future, just want to avoid baking in specific behaviour until I see more apps / what users are doing with it.

**Comment by RReverser** [comment]
Also a side note: except for testing camera-specific functionality, I'd really recommend using ConformU. It helped me find a lot of issues in my own drivers in the past.

I wanted to integrate it into this crate someday, but as it doesn't have programmable API, for now invoking it manually is the only way to go.

**Comment by ivonnyssen** [comment]
I understand the concern of fixing a behavior. Thank you for the conformU info. I am using that as integration test. The PartialEq would help with unit test code - see the example below. When testing multiple outcomes of the same function with rstest checking for the expected outcome of the result now takes a few lines instead of just 

`assert_eq!(result, expected)`

Example
```rust
#[rstest]
#[case(State::Idle, Ok(CameraState::Idle))]
#[case(State::Exposing{ start: SystemTime::UNIX_EPOCH, expected_duration_us: 1_000_u32, stop_tx: None, done_rx: watch::channel(false).1, }, Ok(CameraState::Exposing))]
#[tokio::test]
async fn camera_state(#[case] state: State, #[case] expected: ASCOMResult<CameraState>) {
    //given
    let mock = MockCamera::new();
    let camera = new_camera(mock, MockCameraType::WithState { times: 1, state });
    //when
    let res = camera.camera_state().await;
    //then
    if expected.is_ok() {
        assert_eq!(res.unwrap(), expected.unwrap())
    } else {
        assert_eq!(
            res.unwrap_err().to_string(),
            expected.unwrap_err().to_string()
        );
    }
}
```

**Comment by RReverser** [comment]
> checking for the expected outcome of the result now takes a few lines instead of just
> 
> `assert_eq!(result, expected)`

I think those manual lines can be simplified into

```rust
assert_eq!(result.map_err(|err| err.code), expected)
```

that is, just take the code out of the error instead of doing separate branches and compare that.

Then your expected values can be just `Err(ASCOMErrorCode::SOME_CONST)`.

Would that be enough or do you really need to compare `message` as well?

**Comment by RReverser** [comment]
I decided to look around a bit, and error types with arbitrary messages in the ecosystem (e.g. `anyhow::Error`) also don't implement `PartialEq`, leaving it up to the user to cast them to something else or stringify via `to_string()` for explicit comparisons, so it's probably the right choice for now.

**Comment by ivonnyssen** [comment]
Sounds good and thank you for the help up there! :)
